### PR TITLE
Correct handling of file and header CRC

### PR DESCRIPTION
**Pull request by karl-petter**
Found a bug in the handling of CRC. Old code only calculated the file CRC and set that in the header. And for files with 12 bytes header or with the header CRC set to 0 the reading did not work. This is now corrected and added several test. Unfortunately those tests require files both from Garmin and from ANT that are under a license agreement to not share :( I created the tests so these checks for the files and tells how to get hold of them if missing. If you have a better solution, please let me know.

### CODE REVIEW

**Comment by scrapper** [comment]
Most of your code looks really great! But I have a few asks before I can merge this. It's much easier to review and merge smaller patches that only address one specific issue. E. g. the additional fields.  Please make those a separate merge request. I have refrained from putting FIT files into the repository. I prefer to generate them on the fly by the test cases. While that is debatable, it's certainly not acceptable to include FIT files from the SDK as you point out. But I also don't want to force users that want to run the test suite to download them. I certainly appreciate your TDD focus!

**Comment by karl-petter** [comment]
I have not worked much with pull requests before. How do I remove a commit from a pull request?

Regarding generating files; that methodology kind of covered the CRC problem since both the file generation and the file reading had the same problem so without externally created files it would not have been discovered. And we cannot include these external files and it would be a pity to throw away the test code. Any thoughts on how we can proceed with that part? Can one create optional test that are only run given using a specific rake task? But then it is kind of pointless to have those tests as one wants to have automatic testing? It feels a bit like a catch 22.

**Comment by scrapper** [comment]
Thanks for the fixes. Unfortunately, this patch set conflicts with the current master branch. Can you please rebase and resolve the conflict. There are still some FIT files in the patch. Are you the copyright holder of these files?

**Comment by karl-petter** [comment]
I'll create a new PR. I think there are some more fixes in our branch that can be included. And I was just today investigating an issue with records without a timestamp. But I'll make a separate PR for that.

**Comment by karl-petter** [comment]
Shouldnt have made a PR out of our master branch I realised. I'll close this PR, and from  a seperate new branch create a new PR.

**Pull request closed without merging**
